resolver: lts-22.13
packages:
- .
extra-deps:
- dependent-hashmap-0.1.0.1
- rock-0.3.1.2
- git: https://github.com/ollef/text-rope.git
  commit: 22ccfdd795cfec5014acc3923b781a783afbdb06
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
