resolver: lts-20.26
packages:
- .
extra-deps:
- dependent-hashmap-0.1.0.1
- rock-0.3.1.1
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
- enummapset-0.7.1.0
